pipeline:
  create_cluster:
    image: banzaicloud/plugin-pipeline-client:dev-66ffa94
    cluster_name: "sparkpicluster01"
    cluster_provider: "google"
    google_project: "puski-test-194413"

    secrets: [plugin_endpoint, plugin_username, plugin_password]

  install_monitoring:
    image: banzaicloud/plugin-pipeline-client:dev-66ffa94
    deployment_name: "banzaicloud-stable/pipeline-cluster-monitor"
    deployment_release_name: "monitor"

    secrets: [plugin_endpoint, plugin_username, plugin_password]

  install_spark_history_server:
    image: banzaicloud/plugin-pipeline-client:dev-66ffa94

    deployment_name: "banzaicloud-stable/spark-hs"
    deployment_release_name: "historyserver"
    deployment_values:
      app:
        logDirectory: "gs://puski-testing/data"

    secrets: [plugin_endpoint, plugin_username, plugin_password]

  install_spark_resources:
     image: banzaicloud/plugin-pipeline-client:dev-66ffa94

     deployment_name: "banzaicloud-stable/spark"
     deployment_release_name: "release-1"

     secrets: [plugin_endpoint, plugin_username, plugin_password]

  remote_checkout:
    image: banzaicloud/plugin-k8s-proxy:0.2.0
    original_image: plugins/git

  remote_build:
    image: banzaicloud/plugin-k8s-proxy:0.2.0
    original_image: maven:3.5-jdk-8
    original_commands:
      - mvn clean package

  run:
    image: banzaicloud/plugin-k8s-proxy:0.2.0
    original_image: banzaicloud/plugin-spark-submit-k8s:0.2.0

    pod_service_account: spark
    pull: true
    spark_deploy_mode: cluster

    spark_class: banzaicloud.SparkPi
    spark_app_name: sparkpi
    spark_local_dir: /tmp/spark-local
    spark_packages: "com.google.cloud.bigdataoss:gcs-connector:1.6.3-hadoop2"
    spark_exclude_packages: "org.apache.hadoop:hadoop-common,com.fasterxml.jackson.core:jackson-databind,com.fasterxml.jackson.core:jackson-annotations,com.fasterxml.jackson.core:jackson-core,org.apache.httpcomponents:httpclient,org.apache.httpcomponents:httpcore"

    spark_kubernetes_driver_docker_image: banzaicloud/spark-driver:v2.2.0-k8s-1.0.197
    spark_kubernetes_executor_docker_image: banzaicloud/spark-executor:v2.2.0-k8s-1.0.197
    spark_kubernetes_initcontainer_docker_image: banzaicloud/spark-init:v2.2.0-k8s-1.0.197
    spark_kubernetes_resourcestagingserver_uri: http://spark-rss:10000
    spark_kubernetes_resourcestagingserver_internal_uri: http://spark-rss:10000

    spark_kubernetes_shuffle_labels: "app=spark-shuffle-service,spark-version=2.2.0"
    spark_kubernetes_authenticate_driver_serviceaccount_name: "spark"
    spark_metrics_conf: /opt/spark/conf/metrics.properties

    spark_eventLog_enabled: true
    spark_eventLog_dir: "gs://puski-testing/data"

    spark_app_source: target/spark-pi-1.0-SNAPSHOT.jar
    spark_app_args: 1000
