pipeline:
  create_cluster:
    image: banzaicloud/plugin-pipeline-client:dev-b6fe231
    cluster_name: "sparkpicluster13"
    cluster_provider: "google"
    google_project: "puski-test-194413"
    google_gke_version: "1.8.7-gke.1"
    google_node_count: "2"
    log_level: "debug"

    secrets: [plugin_endpoint, plugin_token]
 
  install_monitoring:
    image: banzaicloud/plugin-pipeline-client:dev-b6fe231
    deployment_name: "banzaicloud-stable/pipeline-cluster-monitor"
    deployment_release_name: "monitor"
    log_level: "debug"

    secrets: [plugin_endpoint, plugin_token]

  install_spark_history_server:
    image: banzaicloud/plugin-pipeline-client:dev-b6fe231

    deployment_name: "banzaicloud-stable/spark-hs"
    deployment_release_name: "historyserver"
    deployment_values:
      app:
        logDirectory: "gs://puski-testing/data"

    secrets: [plugin_endpoint, plugin_token]

  install_spark_resources:
     image: banzaicloud/plugin-pipeline-client:dev-b6fe231

     deployment_name: "banzaicloud-stable/spark"
     deployment_release_name: "release-1"

     secrets: [plugin_endpoint, plugin_token]

  remote_checkout:
    image: banzaicloud/drone-plugin-k8s-client:latest
    original_image: plugins/git

  remote_build:
    image: banzaicloud/drone-plugin-k8s-client:latest
    original_image: maven:3.5-jdk-8
    original_commands:
      - mvn clean package

  run:
    image: banzaicloud/drone-plugin-k8s-client:latest
    original_image: banzaicloud/plugin-spark-submit-k8s:latest
    proxy_service_account: spark
    
    spark_submit_options:
      class: banzaicloud.SparkPi
      kubernetes-namespace: default
      packages: com.google.cloud.bigdataoss:gcs-connector:1.7.0-hadoop2
      exclude-packages: com.fasterxml.jackson.core:jackson-databind,com.fasterxml.jackson.core:jackson-annotations,com.fasterxml.jackson.core:jackson-core
    spark_submit_configs:
      spark.app.name: sparkpi
      spark.local.dir: /tmp/spark-locals
      spark.kubernetes.driver.docker.image: banzaicloud/spark-driver:v2.2.0-k8s-1.0.197
      spark.kubernetes.executor.docker.image: banzaicloud/spark-executor:v2.2.0-k8s-1.0.197
      spark.kubernetes.initcontainer.docker.image: banzaicloud/spark-init:v2.2.0-k8s-1.0.197
      spark.dynamicAllocation.enabled: "true"
      spark.kubernetes.resourceStagingServer.uri: http://spark-rss:10000
      spark.kubernetes.resourceStagingServer.internal.uri: http://spark-rss:10000
      spark.shuffle.service.enabled: "true"
      spark.kubernetes.shuffle.namespace: default
      spark.kubernetes.shuffle.labels: app=spark-shuffle-service,spark-version=2.2.0
      spark.kubernetes.authenticate.driver.serviceAccountName: spark
      spark.metrics.conf: /opt/spark/conf/metrics.properties
      spark.eventLog.enabled: "true"
      spark.eventLog.dir: "gs://puski-testing/data"
    spark_submit_app_args:
      - target/spark-pi-1.0-SNAPSHOT.jar
      - 1000
      
      
      
